package com.ricodevvv.aurora.shape;

import org.bukkit.Location;
import org.bukkit.util.Vector;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ThreadLocalRandom;

/**
 * Curves and trajectories. Every method returns offsets relative to the origin,
 * so the results compose with {@link Shape}'s transforms like any other shape.
 */
public final class Curves {

    private Curves() {
    }

    /**
     * Quadratic Bezier through a single control point.
     *
     * @param from    start point
     * @param control control point
     * @param to      end point
     * @param points  number of samples
     * @return the curve
     */
    public static Shape bezier(Vector from, Vector control, Vector to, int points) {
        List<Vector> list = new ArrayList<>(points);
        for (int i = 0; i <= points; i++) {
            double t = i / (double) points;
            double inv = 1 - t;
            list.add(new Vector(
                    inv * inv * from.getX() + 2 * inv * t * control.getX() + t * t * to.getX(),
                    inv * inv * from.getY() + 2 * inv * t * control.getY() + t * t * to.getY(),
                    inv * inv * from.getZ() + 2 * inv * t * control.getZ() + t * t * to.getZ()));
        }
        return Shape.of(list);
    }

    /**
     * Cubic Bezier through two control points.
     *
     * @param from   start point
     * @param c1     first control point
     * @param c2     second control point
     * @param to     end point
     * @param points number of samples
     * @return the curve
     */
    public static Shape bezier(Vector from, Vector c1, Vector c2, Vector to, int points) {
        List<Vector> list = new ArrayList<>(points);
        for (int i = 0; i <= points; i++) {
            double t = i / (double) points;
            double inv = 1 - t;
            double a = inv * inv * inv, b = 3 * inv * inv * t, c = 3 * inv * t * t, d = t * t * t;
            list.add(new Vector(
                    a * from.getX() + b * c1.getX() + c * c2.getX() + d * to.getX(),
                    a * from.getY() + b * c1.getY() + c * c2.getY() + d * to.getY(),
                    a * from.getZ() + b * c1.getZ() + c * c2.getZ() + d * to.getZ()));
        }
        return Shape.of(list);
    }

    /**
     * Ballistic arc between two locations, for faked projectiles.
     *
     * @param from   start location
     * @param to     end location
     * @param height extra height at the apex
     * @param points number of samples
     * @return the arc
     */
    public static Shape arcBetween(Location from, Location to, double height, int points) {
        Vector start = new Vector(0, 0, 0);
        Vector end = to.toVector().subtract(from.toVector());
        Vector control = new Vector(end.getX() / 2, Math.max(end.getY(), 0) / 2 + height, end.getZ() / 2);
        return bezier(start, control, end, points);
    }

    /**
     * Smooth Catmull-Rom spline passing through every waypoint.
     *
     * <p>Unlike a Bezier, the curve actually touches each control point, which
     * is what you want for camera paths and guided trails.
     *
     * @param waypoints       points the curve must pass through
     * @param pointsPerSegment samples between consecutive waypoints
     * @return the spline
     */
    public static Shape spline(List<Vector> waypoints, int pointsPerSegment) {
        List<Vector> list = new ArrayList<>();
        if (waypoints.size() < 2) return Shape.of(new ArrayList<>(waypoints));

        for (int i = 0; i < waypoints.size() - 1; i++) {
            Vector p0 = waypoints.get(Math.max(0, i - 1));
            Vector p1 = waypoints.get(i);
            Vector p2 = waypoints.get(i + 1);
            Vector p3 = waypoints.get(Math.min(waypoints.size() - 1, i + 2));

            for (int j = 0; j < pointsPerSegment; j++) {
                double t = j / (double) pointsPerSegment;
                list.add(new Vector(
                        catmull(p0.getX(), p1.getX(), p2.getX(), p3.getX(), t),
                        catmull(p0.getY(), p1.getY(), p2.getY(), p3.getY(), t),
                        catmull(p0.getZ(), p1.getZ(), p2.getZ(), p3.getZ(), t)));
            }
        }
        return Shape.of(list);
    }

    private static double catmull(double p0, double p1, double p2, double p3, double t) {
        return 0.5 * ((2 * p1)
                + (-p0 + p2) * t
                + (2 * p0 - 5 * p1 + 4 * p2 - p3) * t * t
                + (-p0 + 3 * p1 - 3 * p2 + p3) * t * t * t);
    }

    /**
     * Jagged lightning bolt, generated by recursive midpoint displacement.
     *
     * <p>Each call produces a different bolt, so regenerating it every few
     * ticks is what makes an animated bolt look alive.
     *
     * @param from   start point
     * @param to     end point
     * @param chaos  maximum displacement at the first subdivision
     * @param detail how many subdivision passes
     * @return the bolt
     */
    public static Shape lightning(Vector from, Vector to, double chaos, int detail) {
        List<Vector> points = new ArrayList<>();
        points.add(from.clone());
        points.add(to.clone());

        for (int pass = 0; pass < detail; pass++) {
            List<Vector> next = new ArrayList<>(points.size() * 2);
            double offset = chaos / (pass + 1);
            for (int i = 0; i < points.size() - 1; i++) {
                Vector a = points.get(i), b = points.get(i + 1);
                next.add(a);
                Vector mid = a.clone().add(b.clone().subtract(a).multiply(0.5));
                mid.add(new Vector(rand(offset), rand(offset), rand(offset)));
                next.add(mid);
            }
            next.add(points.get(points.size() - 1));
            points = next;
        }

        // Densified so the bolt reads as a line rather than scattered dots.
        List<Vector> dense = new ArrayList<>();
        for (int i = 0; i < points.size() - 1; i++) {
            Vector a = points.get(i), b = points.get(i + 1);
            for (int s = 0; s < 4; s++) {
                dense.add(com.ricodevvv.aurora.util.VectorMath.lerp(a, b, s / 4D));
            }
        }
        return Shape.of(dense);
    }

    /**
     * Flat spiral, for whirlpools drawn on the ground.
     *
     * @param radius outer radius
     * @param turns  how many full turns
     * @param points number of points
     * @return the spiral
     */
    public static Shape spiralFlat(double radius, double turns, int points) {
        List<Vector> list = new ArrayList<>(points);
        for (int i = 0; i < points; i++) {
            double t = i / (double) points;
            double angle = Math.PI * 2 * turns * t;
            double r = radius * t;
            list.add(new Vector(Math.cos(angle) * r, 0, Math.sin(angle) * r));
        }
        return Shape.of(list);
    }

    private static double rand(double amount) {
        return (ThreadLocalRandom.current().nextDouble() * 2 - 1) * amount;
    }
}
